remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
 
lsi: false # minimum for github- pages
safe: true # minimum for github- pages
# source: kergadec.github.io # minimum for github- pages
incremental: false # minimum for github- pages
highlighter: rouge # minimum for github- pages
gist: 
  noscript: false # minimum for github- pages
kramdown:
  math_engine: mathjax # minimum for github- pages
  syntax_highlighter: rouge # minimum for github- pages
theme: jekyll-theme-cayman